apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-bw5-app-1210"
  description: BW5CE App - my-bw5-app-1210
  annotations:
    github.com/project-slug: Tibco-Hub-QA/Bw5_DynamicHeaders
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: Tibco-Hub-QA/Bw5_DynamicHeaders
  tibco.developer.hub/topology:
    theme:
      colors:
        background: '#1a237e'
        iconColor: '#1a237e'
    entityIcon:
      icon: ""
      iconTooltip: "BW5CE App"
    statusIcons:
      - icon: 'VerifiedUser'
        iconColor: 'white'
        iconTooltip: 'Scan Passed...'
      - icon: 'CloudDone'
        iconColor: 'white'
        iconTooltip: 'Deployed successfully...'
  tibcoPlatformApps:
    - appType: bw5ce
      appName: my-bw5-app-1210
      dataPlaneName: DP-dev
      dpId: d7tke3818imc7395rnc0
      appId: d7tl04ab8prs73dbuiu0
  links:
    - url: "https://www.tibco.com/"
      title: TIBCO Platform
      icon: dashboard
    - url: "vscode://vscode.git/clone?url=https://github.com/Tibco-Hub-QA/Bw5_DynamicHeaders"
      title: Open in VSCode
      icon: scaffolder
  tags:
    - platform
    - bw5ce

spec:
  type: service
  lifecycle: development
  owner: group:default/tibco-templates
